name: SBOM generation (app and image)
on:
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  sbom-app:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      id-token: write
      
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        
      # SBOM (Maven / CycloneDX)
      # Sign sbom
      - name: Generate SBOM (Application)
        run: mvn -B org.cyclonedx:cyclonedx-maven-plugin:2.8.0:makeAggregateBom

      - name: Install cosign
        uses: sigstore/cosign-installer@v3

      - name: Sign SBOM Application
        run: |
          cosign sign-blob \
            --yes \
            target/bom.json \
            --output-signature sbom-app.sig \
            --output-certificate sbom-app.crt

      - name: Upload SBOM Application (+sig +crt)
        uses: actions/upload-artifact@v4
        with:
          name: sbom-application
          path: |
            target/bom.json
            sbom-aplication.sig
            sbom-application.crt
