name: Build Pipeline v1 Lab1

on:
  workflow_dispatch:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
      
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # Testes unitários
      - name: Build e testes (JUnit)
        run: mvn clean test

      # CodeQL - análise estática de código
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: java
          
      - name: Build for CodeQL Analysis
        run: mvn clean compile
          
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4

      # Trivy
      - name: Scan Completo com Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'fs'                      
          scanners: 'vuln,secret,config'     
          severity: 'CRITICAL,HIGH'
          format: 'sarif'
          output: 'trivy-results.sarif'
      
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy-results.sarif

      - uses: actions/upload-artifact@v4
        with:
          name: Generate artifact with Trivy result
          path: trivy-results.sarif

